services:
  backend:
    image: minikanva/url-backend:latest
    container_name: url-backend
    ports:
      - "4000:4000"
    restart: always

  frontend:
    image: minikanva/url-frontend:latest
    container_name: url-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
